name: Feature request
description: Suggest an idea for this project
title: "[enhancement] "
labels: ["enhancement"]
assignees:
  - dotdc
# Doc: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
body:
  - type: markdown
    attributes:
      value: |
        **Please make sure you don't accidentally share sensitive information while filing this issue.**

  - type: textarea
    attributes:
      label: Describe the enhancement you'd like
      description: A clear and concise description of what should be added to this project.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context about your feature request here.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
